language: ruby
cache:
  bundler: true
addons:
  chrome: stable
services:
  - redis-server
before_install:
  - gem install bundler
script:
  - bundle exec rails db:test:prepare
  - bundle exec rubocop app spec config
  - bundle exec rails spec
